### ISSUE TITLE
Issues with Docker image

### ISSUE THREAD

**Issue by surrutiaquir** [GambitBSM/gambit_2.5#2]
I have been using the pre-built version of GAMBIT available as a Docker image, and everything seemed to work until I modified a few functions in the `NeutrinoBit` sector:

```
NeutrinoBit/include/gambit/NeutrinoBit/NeutrinoBit_rollcall.hpp
NeutrinoBit/src/NeutrinoBit.cpp
NeutrinoBit/src/RightHandedNeutrinos.cpp
```

I recompiled the running container, and I got the following error message at the very end:

```
[100%] Building CXX object CMakeFiles/gambit.dir/Core/src/gambit.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/gambit.dir/build.make:76: CMakeFiles/gambit.dir/Core/src/gambit.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:15340: CMakeFiles/gambit.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:15347: CMakeFiles/gambit.dir/rule] Error 2
make: *** [Makefile:7066: gambit] Error 2
```

Do you know what might be causing this? I am happy to provide further details. Thanks!

**Comment by andrewfowlie** [comment]
Hi there,

I’m not certain, but you may have run out of memory. Can you run 

sudo dmesg

immediately after the crash? It will give more information. How much memory does your computer have? Did you run make in parallel eg make -j4 ?

Best,

Andrew

**Comment by patscott** [comment]
As Andrew suggests, this is almost certainly due to running out of memory.  

It could be that you have more memory available but your Docker setup isn't configured to allow it to be used within your container.  See e.g. https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container.

**Comment by surrutiaquir** [comment]
Thank you, @patscott and @andrewfowlie. That was exactly the problem, and the suggested link helped me to fix it. You are a great team!

**Comment by andrewfowlie** [comment]
That’s great! Thank you for your kind feedback! Please don’t hesitate to let us know if you have any other issues.

Best,

Andrew
